name: Build and Deploy Frontend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build app
        run: |
          npx vite build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_JAYDIENPORTAL }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_JAYDIENPORTAL }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_JAYDIENPORTAL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jaydien-portal'
          package: dist
